#!/usr/bin/with-contenv bash

touch config/config.yml
yasha config/base.j2 --no-variable-file -o config/config.yml
echo $FLEXGET_LOG_LEVEL
if [ "$FLEXGET_LOG_LEVEL" == "debug" ]; then
 cat /config/config.yml
fi