web_server: {{ "yes" | env_override('WEBSERVER') }}

schedules:
  - tasks: '*'
    interval:
      minutes: ${INTERVAL}

tasks:
  gp task:
    rss: ${RSS}
    accept_all: yes
    transmission:
      host: ${TRANSMISSION_HOST}
      port: ${TRANSMISSION_PORT}
      username: ${TRANSMISSION_USER}
      password: ${TRANSMISSION_PASS}
