web_server: {{ "yes" | env_override('WEBSERVER') }}

schedules:
  - tasks: '*'
    interval:
      minutes: {{ "5" | env_override('INTERVAL') }}

tasks:
  gp task:
    rss: {{ env_override('RSS') }}
    accept_all: yes
    transmission:
      host: {{ env_override('TRANSMISSION_HOST') }}
      port: {{ env_override('TRANSMISSION_PORT') }}
      username: {{ env_override('TRANSMISSION_USER') }}
      password: {{ env_override('TRANSMISSION_PASS') }}
